namespace TokenCs;

/// <summary>
/// A single token generated by a <see cref="Tokenizer"/>.
/// </summary>
/// <param name="Index">Index of this token relative to the Enumerable it was parsed from.</param>
/// <param name="Text">Full text span of this token.</param>
/// <param name="Type">Type of this token.</param>
public record Token(int Index, string Text, TokenType Type)
{
    /// <inheritdoc />
    public override string ToString()
    {
        return Text;
    }
}